'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Smartik.Ecom.Web.Administration.Modules

    Partial Public Class SponsorPaymentHistoryControl
    End Class
End Namespace
