'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Smartik.Administration

    Partial Public Class rptButterflySummaryPage

        '''<summary>
        '''ctrlSummButterfly control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctrlSummButterfly As Global.GGBC.Smartik.Administration.Reports.SummaryButterflyControl
    End Class
End Namespace
