'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Smartik.Administration.Modules

    Partial Public Class ConfirmationBox

        '''<summary>
        '''cbe control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbe As Global.AjaxControlToolkit.ConfirmButtonExtender

        '''<summary>
        '''mpe control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents mpe As Global.AjaxControlToolkit.ModalPopupExtender

        '''<summary>
        '''pnlPopup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPopup As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lConfirmText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lConfirmText As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''btnYES control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnYES As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''btnNO control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnNO As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
