'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Smartik.Administration.Modules

    Partial Public Class DecimalTextBox

        '''<summary>
        '''txtValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtValue As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ftbeValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ftbeValue As Global.AjaxControlToolkit.FilteredTextBoxExtender

        '''<summary>
        '''rfvValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvValue As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''rvValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rvValue As Global.System.Web.UI.WebControls.RangeValidator

        '''<summary>
        '''rfvValueE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rfvValueE As Global.AjaxControlToolkit.ValidatorCalloutExtender

        '''<summary>
        '''rvValueE control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rvValueE As Global.AjaxControlToolkit.ValidatorCalloutExtender
    End Class
End Namespace
