'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Smartik.Administration.Modules

    Partial Public Class GrantBeneficiaryControl

        '''<summary>
        '''hfSponsorId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfSponsorId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hlReturn control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlReturn As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lblGGBCRegNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblGGBCRegNo As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtGGBCRegNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtGGBCRegNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''SearchButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SearchButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''gvGrantBeneficiary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvGrantBeneficiary As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''lblNoRecords control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNoRecords As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''btnSave control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
