'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Smartik.Administration.Modules

    Partial Public Class MenteeDetailsControl

        '''<summary>
        '''lblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''SaveButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SaveButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''SaveAndStayButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SaveAndStayButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''MenteeTabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MenteeTabs As Global.AjaxControlToolkit.TabContainer

        '''<summary>
        '''pnlMenteeInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlMenteeInfo As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''ctrlMenteeInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctrlMenteeInfo As Global.GGBC.Smartik.Administration.Modules.MenteeInfoControl

        '''<summary>
        '''pnlSchoolInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSchoolInfo As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''ctrlMenteeSchool control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctrlMenteeSchool As Global.GGBC.Smartik.Administration.Modules.MenteeSchoolControl

        '''<summary>
        '''pnlCommitmentInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlCommitmentInfo As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''ctrlCommitmentInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctrlCommitmentInfo As Global.GGBC.Smartik.Administration.Modules.MenteeCommitmentInfoControl

        '''<summary>
        '''pnlInternshipInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlInternshipInfo As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''ctrlInternshipInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctrlInternshipInfo As Global.GGBC.Smartik.Administration.Modules.MenteeInternshipInfoControl

        '''<summary>
        '''pnlWorkshopInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlWorkshopInfo As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''ctrlWorkshopInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctrlWorkshopInfo As Global.GGBC.Smartik.Administration.Modules.MenteeWorkshopControl

        '''<summary>
        '''pnlButterflyInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlButterflyInfo As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''ctrlButterflyInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctrlButterflyInfo As Global.GGBC.Smartik.Administration.Modules.MenteeButterflyInfoControl

        '''<summary>
        '''pnlSocietalLaunch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSocietalLaunch As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''ctrlMenteeSocietalLaunch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctrlMenteeSocietalLaunch As Global.GGBC.Smartik.Administration.Modules.MenteeSocietalLaunchControl
    End Class
End Namespace
