'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Smartik.Administration.Modules

    Partial Public Class MenteeSchoolControl

        '''<summary>
        '''ToolTipLabel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel1 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''ddSecSchool control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddSecSchool As Global.GGBC.Smartik.Administration.Modules.ddlSchoolSelectorControl

        '''<summary>
        '''ToolTipLabel2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel2 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtSecSchoolSponsor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSecSchoolSponsor As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ToolTipLabel3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel3 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtSecAmount1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSecAmount1 As Global.Smartik.Ecom.Controls.STKDecimalTextBox

        '''<summary>
        '''ToolTipLabel4 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel4 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''ddClass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddClass As Global.GGBC.Smartik.Administration.Modules.ddlSelectorControl

        '''<summary>
        '''ToolTipLabel5 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel5 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtAnticipatedgradyear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAnticipatedgradyear As Global.Smartik.Ecom.Controls.STKDatePicker

        '''<summary>
        '''ToolTipLabel6 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel6 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtActualGradYear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtActualGradYear As Global.Smartik.Ecom.Controls.STKDatePicker

        '''<summary>
        '''ToolTipLabel7 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel7 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''ddKCSEscore control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddKCSEscore As Global.GGBC.Smartik.Administration.Modules.ddlSelectorControl

        '''<summary>
        '''ToolTipLabel8 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel8 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtdateofICTcourse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtdateofICTcourse As Global.Smartik.Ecom.Controls.STKDatePicker

        '''<summary>
        '''ToolTipLabel9 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel9 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''ddICTTraining control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddICTTraining As Global.GGBC.Smartik.Administration.Modules.ddlSchoolSelectorControl

        '''<summary>
        '''ToolTipLabel10 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel10 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''ddICTCompleted control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddICTCompleted As Global.GGBC.Smartik.Administration.Modules.ddlSelectorControl

        '''<summary>
        '''ToolTipLabel11 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel11 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''ddMScertification control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddMScertification As Global.GGBC.Smartik.Administration.Modules.ddlSelectorControl

        '''<summary>
        '''ToolTipLabel12 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel12 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''ddMScertresults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddMScertresults As Global.GGBC.Smartik.Administration.Modules.ddlSelectorControl

        '''<summary>
        '''ToolTipLabel13 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel13 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''ddCiscocertification control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddCiscocertification As Global.GGBC.Smartik.Administration.Modules.ddlSelectorControl

        '''<summary>
        '''ToolTipLabel14 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel14 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''ddCiscocertresults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddCiscocertresults As Global.GGBC.Smartik.Administration.Modules.ddlSelectorControl

        '''<summary>
        '''ToolTipLabel15 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel15 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''ddTertiarySchool control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddTertiarySchool As Global.GGBC.Smartik.Administration.Modules.ddlSelectorControl

        '''<summary>
        '''ToolTipLabel16 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel16 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''ddTertiary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddTertiary As Global.GGBC.Smartik.Administration.Modules.ddlSchoolSelectorControl

        '''<summary>
        '''ToolTipLabel17 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel17 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtTertSchaddr1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTertSchaddr1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ToolTipLabel18 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel18 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtTertSchaddr2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTertSchaddr2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ToolTipLabel19 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel19 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtTertSchaddr3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTertSchaddr3 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ToolTipLabel20 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel20 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtTerSchsponsor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTerSchsponsor As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ToolTipLabel21 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel21 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtTertSchAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTertSchAmount As Global.Smartik.Ecom.Controls.STKDecimalTextBox

        '''<summary>
        '''ToolTipLabel22 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel22 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtDateJoinedTert control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtDateJoinedTert As Global.Smartik.Ecom.Controls.STKDatePicker

        '''<summary>
        '''ToolTipLabel23 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel23 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtExpectedtertgraddate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExpectedtertgraddate As Global.Smartik.Ecom.Controls.STKDatePicker

        '''<summary>
        '''ToolTipLabel24 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel24 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtActualtertgraddate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtActualtertgraddate As Global.Smartik.Ecom.Controls.STKDatePicker

        '''<summary>
        '''ToolTipLabel25 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel25 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''ddCourse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddCourse As Global.GGBC.Smartik.Administration.Modules.ddlSelectorControl

        '''<summary>
        '''ToolTipLabel26 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel26 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''ddDegreeEarned control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddDegreeEarned As Global.GGBC.Smartik.Administration.Modules.ddlSelectorControl

        '''<summary>
        '''ToolTipLabel27 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel27 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''ddConcentration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddConcentration As Global.GGBC.Smartik.Administration.Modules.ddlSelectorControl
    End Class
End Namespace
