'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Smartik.Administration.Modules

    Partial Public Class ReceivePaymentsControl

        '''<summary>
        '''hlExit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlExit As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''lblAgreedPaymentAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAgreedPaymentAmount As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''lblMatchAgreedAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMatchAgreedAmount As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''hfSponsorName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfSponsorName As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''hfSponsorId control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfSponsorId As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''lblBalanceTooltip control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBalanceTooltip As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''lblExistingBalance control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblExistingBalance As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''ToolTipLabel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel1 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''ctrlNewPaymentDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctrlNewPaymentDate As Global.GGBC.Smartik.Administration.Modules.DatePicker

        '''<summary>
        '''lblAmountReceived control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAmountReceived As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''hfPaymentAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfPaymentAmount As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''labelNewBalance control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents labelNewBalance As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''lblNewBalance control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNewBalance As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''hfNewBalance control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfNewBalance As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''PostPayment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PostPayment As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''gvGrantPayments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvGrantPayments As Global.System.Web.UI.WebControls.GridView
    End Class
End Namespace
