'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Smartik.Administration.Modules

    Partial Public Class SchoolInfoControl

        '''<summary>
        '''pnlData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlData As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblSchoolName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSchoolName As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtSchoolName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSchoolName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''hfSchoolName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hfSchoolName As Global.System.Web.UI.WebControls.HiddenField

        '''<summary>
        '''ToolTipLabel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel1 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''ctrlTypoSchool control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctrlTypoSchool As Global.GGBC.Smartik.Administration.Modules.TypoSchoolControl

        '''<summary>
        '''lblSchooladdressLine1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSchooladdressLine1 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtSchoolAddressLn1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSchoolAddressLn1 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblSchooladdressLine2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSchooladdressLine2 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtSchoolAddressLn2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSchoolAddressLn2 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblSchooladdressLine3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSchooladdressLine3 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtSchoolAddressLn3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSchoolAddressLn3 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblContactFname control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblContactFname As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtContactFname control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtContactFname As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblContactLname control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblContactLname As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtContactLname control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtContactLname As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitle As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''ddlContactTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlContactTitle As Global.GGBC.Smartik.Administration.Modules.ddlSelectorControl

        '''<summary>
        '''ToolTipLabel2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel2 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''ctrlTypoSchoolSpec control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctrlTypoSchoolSpec As Global.GGBC.Smartik.Administration.Modules.TypoSchoolSpecificControl

        '''<summary>
        '''lblContactPhoneno control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblContactPhoneno As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtContactPhoneno control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtContactPhoneno As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblContactEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblContactEmail As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmail As Global.GGBC.Smartik.Administration.Modules.EmailTextBox

        '''<summary>
        '''lblDatejoinedGGBC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDatejoinedGGBC As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''ctrlDateJoinedGGBC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctrlDateJoinedGGBC As Global.Smartik.Ecom.Controls.STKDatePicker

        '''<summary>
        '''lblCountry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCountry As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''ddlCountry control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCountry As Global.GGBC.Smartik.Administrator.Modules.CountrySelectorControl

        '''<summary>
        '''lblNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNotes As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtNotes control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtNotes As Global.System.Web.UI.WebControls.TextBox
    End Class
End Namespace
