'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Smartik.Administration.Modules

    Partial Public Class SponsorGrantControl

        '''<summary>
        '''lblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''pnlData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlData As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''upGrants control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents upGrants As Global.System.Web.UI.UpdatePanel

        '''<summary>
        '''pnlError control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlError As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lErrorTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lErrorTitle As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''gvGrants control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gvGrants As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''lblMatchAmountAgreed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMatchAmountAgreed As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtMatchAmountAgreed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMatchAmountAgreed As Global.Smartik.Ecom.Controls.STKDecimalTextBox

        '''<summary>
        '''lblPaymentType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPaymentType As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''ddlTypeOfPayment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlTypeOfPayment As Global.GGBC.Smartik.Administration.Modules.ddlSelectorControl

        '''<summary>
        '''ToolTipLabel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel1 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''ctrlBeginDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctrlBeginDate As Global.GGBC.Smartik.Administration.Modules.DatePicker

        '''<summary>
        '''ToolTipLabel2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ToolTipLabel2 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''ctrlEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctrlEndDate As Global.GGBC.Smartik.Administration.Modules.DatePicker

        '''<summary>
        '''btnNewGrant control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnNewGrant As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''up1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents up1 As Global.System.Web.UI.UpdateProgress
    End Class
End Namespace
