'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Smartik.Administration.Modules

    Partial Public Class SponsorGrantInfo1Control

        '''<summary>
        '''pnlData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlData As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''lblBeginDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBeginDate As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''dtBeginDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dtBeginDate As Global.Smartik.Ecom.Controls.STKDatePicker

        '''<summary>
        '''lblEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblEndDate As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''dtEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dtEndDate As Global.Smartik.Ecom.Controls.STKDatePicker

        '''<summary>
        '''lblTypeOfPayment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTypeOfPayment As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''ddlTypeOfPayment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlTypeOfPayment As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblAgreedGrantAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAgreedGrantAmount As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtAgreedGrantAmount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAgreedGrantAmount As Global.GGBC.Smartik.Administration.Modules.DecimalTextBox

        '''<summary>
        '''lblCompanyaddressLine3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCompanyaddressLine3 As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtCompanyAddressLn3 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCompanyAddressLn3 As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblPriContactFname control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPriContactFname As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtPriContactFname control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPriContactFname As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblPriContactLname control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPriContactLname As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtPriContactLname control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPriContactLname As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitle As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''cmbTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmbTitle As Global.AjaxControlToolkit.ComboBox

        '''<summary>
        '''lblPriContactPhoneno control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPriContactPhoneno As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtPriContactPhoneno control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPriContactPhoneno As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblPriContactEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPriContactEmail As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtPriContactEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPriContactEmail As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblSecContactFname control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSecContactFname As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtSecContactFname control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSecContactFname As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblSecContactLname control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSecContactLname As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtSecContactLname control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSecContactLname As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblSecTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSecTitle As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''cmbSecTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmbSecTitle As Global.AjaxControlToolkit.ComboBox

        '''<summary>
        '''lblSecContactPhoneno control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSecContactPhoneno As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtSecContactPhoneno control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSecContactPhoneno As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblSecContactEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSecContactEmail As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtSecContactEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSecContactEmail As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''lblDatejoinedGGBC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDatejoinedGGBC As Global.GGBC.Smartik.Administration.Modules.ToolTipLabelControl

        '''<summary>
        '''txtdatejoinedGGBC control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtdatejoinedGGBC As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''Imgdatejoinedggbc control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Imgdatejoinedggbc As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''clDOB control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents clDOB As Global.AjaxControlToolkit.CalendarExtender
    End Class
End Namespace
