'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace Smartik.Administration.Modules

    Partial Public Class SponsorDetailsControl

        '''<summary>
        '''lblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''SaveButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SaveButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''SaveAndStayButton control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SaveAndStayButton As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''SponsorTabs control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents SponsorTabs As Global.AjaxControlToolkit.TabContainer

        '''<summary>
        '''pnlSponsorInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlSponsorInfo As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''ctrlSponsorInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctrlSponsorInfo As Global.GGBC.Smartik.Administration.Modules.SponsorInfoControl

        '''<summary>
        '''pnlPartnerMeetings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlPartnerMeetings As Global.AjaxControlToolkit.TabPanel

        '''<summary>
        '''ctrlSponsorMeetings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctrlSponsorMeetings As Global.GGBC.Smartik.Administration.Modules.SponsorMeetingsControl
    End Class
End Namespace
